/* 🤖 this file was generated by svg-to-ts */
export var fiArrowDownLeft24Filled = {
    name: 'arrow_down_left_24_filled',
    data: "<svg width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M13 21a1 1 0 000-2H6.41l14.3-14.3a1 1 0 00-1.42-1.4L5 17.58V11a1 1 0 10-2 0v9a1 1 0 001 1h9z\"/></svg>"
};
