/* 🤖 this file was generated by svg-to-ts */
export var fiChevronDown24Regular = {
    name: 'chevron_down_24_regular',
    data: "<svg width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M4.22 8.47c.3-.3.77-.3 1.06 0L12 15.19l6.72-6.72a.75.75 0 111.06 1.06l-7.25 7.25c-.3.3-.77.3-1.06 0L4.22 9.53a.75.75 0 010-1.06z\"/></svg>"
};
