/* 🤖 this file was generated by svg-to-ts */
export var fiCellularData524Regular = {
    name: 'cellular_data_5_24_regular',
    data: "<svg width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M3 17.75v1.5a.75.75 0 001.5 0v-1.5a.75.75 0 00-1.5 0z\"/></svg>"
};
