/* 🤖 this file was generated by svg-to-ts */
export var fiNavigation24Filled = {
    name: 'navigation_24_filled',
    data: "<svg width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M3 17h18a1 1 0 01.12 2H3a1 1 0 01-.12-2H21 3zm0-6h18a1 1 0 01.12 2H3a1 1 0 01-.12-2H21 3zm0-6h18a1 1 0 01.12 2H3a1 1 0 01-.12-2H21 3z\"/></svg>"
};
