/* 🤖 this file was generated by svg-to-ts */
export var fiPresenceBusy24Filled = {
    name: 'presence_busy_24_filled',
    data: "<svg width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M24 12a12 12 0 11-24 0 12 12 0 0124 0z\"/></svg>"
};
