/* 🤖 this file was generated by svg-to-ts */
export var fiSubtract24Filled = {
    name: 'subtract_24_filled',
    data: "<svg width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M4 13h16a1 1 0 100-2H4a1 1 0 100 2z\"/></svg>"
};
