/* 🤖 this file was generated by svg-to-ts */
export var fiTextBulletListRotate27024Regular = {
    name: 'text_bullet_list_rotate_270_24_regular',
    data: "<svg width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M17.5 20.75a1.25 1.25 0 112.5 0 1.25 1.25 0 01-2.5 0zm.5-3.5V2.75a.75.75 0 011.5-.1v14.6a.75.75 0 01-1.5.1v-.1zm-7 3.5a1.25 1.25 0 112.5 0 1.25 1.25 0 01-2.5 0zm.5-3.5V2.75a.75.75 0 011.5-.1v14.6a.75.75 0 01-1.5.1v-.1zm-7 3.5a1.25 1.25 0 112.5 0 1.25 1.25 0 01-2.5 0zm.5-3.5V2.75a.75.75 0 011.5-.1v14.6a.75.75 0 01-1.5.1v-.1z\"/></svg>"
};
