/* 🤖 this file was generated by svg-to-ts */
export var fiTextBulletListRotate9024Filled = {
    name: 'text_bullet_list_rotate_90_24_filled',
    data: "<svg width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M7.5 3.5a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0zm-.5 4V21a1 1 0 01-2 .12V7.5a1 1 0 012-.12v.12zm6.5-4a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0zm-.5 4V21a1 1 0 01-2 .12V7.5a1 1 0 012-.12v.12zm6.5-4a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0zm-.5 4V21a1 1 0 01-2 .12V7.5a1 1 0 012-.12v.12z\"/></svg>"
};
