/* 🤖 this file was generated by svg-to-ts */
export var fiTextIndentDecreaseRotate27024Filled = {
    name: 'text_indent_decrease_rotate_270_24_filled',
    data: "<svg width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M16 15V6.5a1 1 0 012-.12V15a1 1 0 01-2 .12V15zm-4.7 6.7l-2-2a1 1 0 011.31-1.49l.1.08L12 19.6l1.3-1.3a1 1 0 011.49 1.32l-.08.1-2 2a1 1 0 01-1.32.08l-.1-.08zM11 15V3.5a1 1 0 012-.12V15a1 1 0 01-2 .12V15zm-5 0V6.5a1 1 0 012-.12V15a1 1 0 01-2 .12V15z\"/></svg>"
};
