/* 🤖 this file was generated by svg-to-ts */
export var fiTextBulletListRotate27024Filled = {
    name: 'text_bullet_list_rotate_270_24_filled',
    data: "<svg width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M16.5 20.5a1.5 1.5 0 113 0 1.5 1.5 0 01-3 0zm.5-4V3a1 1 0 012-.12V16.5a1 1 0 01-2 .12v-.12zm-6.5 4a1.5 1.5 0 113 0 1.5 1.5 0 01-3 0zm.5-4V3a1 1 0 012-.12V16.5a1 1 0 01-2 .12v-.12zm-6.5 4a1.5 1.5 0 113 0 1.5 1.5 0 01-3 0zm.5-4V3a1 1 0 012-.12V16.5a1 1 0 01-2 .12v-.12z\"/></svg>"
};
